services:
  ngcash_db:
    image: postgres
    container_name: ngcash_db
    restart: always
    ports:
      - 3456:5432
    env_file:
      - backend/.env
    volumes:
      - ngcash_db:/var/lib/postgresql/data

  ngcash_app:
    container_name: ngcash_app
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - ngcash_db
    env_file:
      - backend/.env
  ngcash_react:
    container_name: ngcash_react
    build: ./frontend
    volumes:
      - build-react:/var/www/html

  ngcash_nginx:
    container_name: ngcash_nginx
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build-react:/var/www/html
    depends_on:
      - ngcash_db
      - ngcash_app
      - ngcash_react
volumes:
  ngcash_db:
  build-react:
